//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.09.21 at 02:02:25 PM MSK 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://misha/doctorapp/generator", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package misha.doctorapp.generator;
